colores = {
    'SILVER': 'plata',
    'BLACK': 'negro',
    'PINK': 'rosa',
    'MID BLUE': 'azul',
    'LIGHT BLUE': 'azul',
    'CREAM': 'crema',
    'YELLOW': 'amarillo',
    'WHITE': 'blanco',
    'ORANGE': 'naranja',
    'PURPLE': 'morado',
    'BROWN': 'marrón',
    'BEIGE': 'beige',
    'GREY': 'gris',
    'BLUE': 'azul',
    'NAVY': 'azul',
    'GREEN': 'verde',
    'RED': 'rojo',
    'DARK BROWN': 'marrón',
    'GREEN/RED': 'verde/rojo',
    'GREEN/MULTI': 'verde',
    'IVORY': 'beige',
    'TAUPE': 'topo',
    'DARK RED': 'rojo',
    'RED/MULTI': 'rojo',
    'MERLOT': 'granate',
    'MAROON': 'granate',
    'SANDSHELL': 'beige',
    'OLIVE': 'verde',
    'EMERALD': 'verde',
    'EGRET': 'blanco',
    'PINK/MULTI': 'rosa',
    'BLACK/BLACK': 'negro',
    'HEATHER GREY': 'gris',
    'BURGUNDY': 'granate',
    'HUNTER GREEN': 'verde',
    'WINE': 'granate',
    'BLACK/NUDE': 'negro',
    'OLIVINE /BLACK': 'verde',
    'BLACK/MULTI': 'negro',
    'RED/WHITE': 'rojo/blanco',
    'VANILLA': 'beige'
}